"""add_admin_reseller_gateway_fields

Revision ID: 0b4dc403895c
Revises: a05ae4625178
Create Date: 2026-07-01 03:40:49.896451
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4dc403895c'
down_revision: Union[str, None] = 'a05ae4625178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_messages', sa.Column('batch_number', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_sms_messages_batch_number'), 'sms_messages', ['batch_number'], unique=False)
    op.add_column('users', sa.Column('credit_rate', sa.Numeric(precision=10, scale=4), nullable=False, server_default="1.0"))
    op.add_column('users', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['parent_id'], ['id'])
    
    # Check if table already exists
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    if 'sms_gateways' not in tables:
        op.create_table(
            'sms_gateways',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('api_url', sa.String(length=500), nullable=False),
            sa.Column('api_key', sa.String(length=500), nullable=False),
            sa.Column('weight', sa.Integer(), nullable=False, server_default="50"),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default="true"),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms_gateways')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'parent_id')
    op.drop_column('users', 'credit_rate')
    op.drop_index(op.f('ix_sms_messages_batch_number'), table_name='sms_messages')
    op.drop_column('sms_messages', 'batch_number')
    # ### end Alembic commands ###
