"""add_sms_email_2fa

Revision ID: 331a40cd5b01
Revises: fc9332da59cd
Create Date: 2026-07-08 22:14:37.158995
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331a40cd5b01'
down_revision: Union[str, None] = 'fc9332da59cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_method', sa.String(length=20), nullable=False, server_default=sa.text("'totp'")))
    op.add_column('users', sa.Column('otp_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_code')
    op.drop_column('users', 'two_factor_method')
    # ### end Alembic commands ###
