"""add_scheduled_at_to_sms_messages

Revision ID: 5fef3574b66b
Revises: 0b4dc403895c
Create Date: 2026-07-01 03:52:25.213926
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fef3574b66b'
down_revision: Union[str, None] = '0b4dc403895c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_messages', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_messages', 'scheduled_at')
    # ### end Alembic commands ###
