"""add_webhook_and_sender_id_and_inquiries

Revision ID: 65b795317ae8
Revises: 
Create Date: 2026-06-30 21:19:31.935866
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b795317ae8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'contact_groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('webhook_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'webhook_url')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'group_id')
    # ### end Alembic commands ###
