"""add_sms_templates_table

Revision ID: 71e8d5c0c009
Revises: 5fef3574b66b
Create Date: 2026-07-01 13:54:03.274508
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e8d5c0c009'
down_revision: Union[str, None] = '5fef3574b66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
