"""add_indexes_timestamps_soft_deletes

Revision ID: a05ae4625178
Revises: 65b795317ae8
Create Date: 2026-06-30 22:37:23.630483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05ae4625178'
down_revision: Union[str, None] = '65b795317ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.add_column('campaigns', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.add_column('contact_groups', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_contact_groups_user_id'), 'contact_groups', ['user_id'], unique=False)
    op.add_column('contacts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('sender_id_requests', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('sms_messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_sms_messages_status'), 'sms_messages', ['status'], unique=False)
    op.create_index(op.f('ix_sms_messages_user_id'), 'sms_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_sms_messages_user_id'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_status'), table_name='sms_messages')
    op.drop_column('sms_messages', 'deleted_at')
    op.drop_column('sender_id_requests', 'updated_at')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_column('notifications', 'updated_at')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_column('contacts', 'deleted_at')
    op.drop_index(op.f('ix_contact_groups_user_id'), table_name='contact_groups')
    op.drop_column('contact_groups', 'deleted_at')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_column('campaigns', 'deleted_at')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_column('api_keys', 'updated_at')
    # ### end Alembic commands ###
