"""add_api_key_advanced_fields

Revision ID: ac4bb408f1b5
Revises: 71e8d5c0c009
Create Date: 2026-07-02 01:57:31.944231
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4bb408f1b5'
down_revision: Union[str, None] = '71e8d5c0c009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('scope', sa.String(length=50), nullable=False))
    op.add_column('api_keys', sa.Column('rate_limit', sa.Integer(), nullable=False))
    op.add_column('api_keys', sa.Column('ip_whitelist', sa.String(length=255), nullable=True))
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'ip_whitelist')
    op.drop_column('api_keys', 'rate_limit')
    op.drop_column('api_keys', 'scope')
    # ### end Alembic commands ###
