"""split_sandbox_and_live_states

Revision ID: d09872c80f40
Revises: b7a8e2f34d91
Create Date: 2026-07-09 00:06:02.514707
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09872c80f40'
down_revision: Union[str, None] = 'b7a8e2f34d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('sandbox_mode', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('incoming_sms', sa.Column('sandbox_mode', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('notifications', sa.Column('sandbox_mode', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('sender_id_requests', sa.Column('sandbox_mode', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('sms_messages', sa.Column('sandbox_mode', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('sms_templates', sa.Column('sandbox_mode', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('transactions', sa.Column('sandbox_mode', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('sandbox_sms_balance', sa.Integer(), server_default=sa.text('10000'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sandbox_sms_balance')
    op.drop_column('transactions', 'sandbox_mode')
    op.drop_column('sms_templates', 'sandbox_mode')
    op.drop_column('sms_messages', 'sandbox_mode')
    op.drop_column('sender_id_requests', 'sandbox_mode')
    op.drop_column('notifications', 'sandbox_mode')
    op.drop_column('incoming_sms', 'sandbox_mode')
    op.drop_column('campaigns', 'sandbox_mode')
    # ### end Alembic commands ###
