"""add_api_key_sandbox_field

Revision ID: e0df7f92e736
Revises: f2592a1d6f16
Create Date: 2026-07-02 14:15:24.343489
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0df7f92e736'
down_revision: Union[str, None] = 'f2592a1d6f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('is_sandbox', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'is_sandbox')
    # ### end Alembic commands ###
