"""add_contact_custom_attributes

Revision ID: e449c8a3852b
Revises: e0df7f92e736
Create Date: 2026-07-04 03:48:21.186796
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e449c8a3852b'
down_revision: Union[str, None] = 'e0df7f92e736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable first
    op.add_column('contacts', sa.Column('custom_attributes', sa.JSON(), nullable=True))
    # 2. Populate default empty JSON object for existing rows
    op.execute("UPDATE contacts SET custom_attributes = '{}' WHERE custom_attributes IS NULL")
    # 3. Apply NOT NULL constraint
    op.alter_column('contacts', 'custom_attributes', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'custom_attributes')
    # ### end Alembic commands ###
