"""add_api_key_max_credits

Revision ID: f2592a1d6f16
Revises: ac4bb408f1b5
Create Date: 2026-07-02 02:04:27.861008
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2592a1d6f16'
down_revision: Union[str, None] = 'ac4bb408f1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('max_credits', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'max_credits')
    # ### end Alembic commands ###
